Category.create(name: "Shooting")
Category.create(name: "Passing")
Category.create(name: "Heading")
Category.create(name: "Tackling")
Category.create(name: "Dribbling")
Category.create(name: "Conditioning")